on: [push]

jobs:
  copyright_job:
    runs-on: ubuntu-latest
    name: A job to check copyright
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update copyrights
        uses: ./
